sudo: required

python:
  - "3.5"

services:
    - docker

before_install:
    - docker pull opendataservices/resource-projects-etl:${TRAVIS_TAG:-$TRAVIS_BRANCH}
    - docker build -t opendataservices/resource-projects-etl .
    - docker run -p 127.0.0.1:8000:80 opendataservices/resource-projects-etl
    - pip install -r requirements_test.txt

script:
    - SERVER_URL=http://localhost:8000 py.test fts

after_success:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push opendataservices/resource-projects-etl
    - if [[ $TRAVIS_PULL_REQUEST -eq "false" ]]; then docker tag opendataservices/resource-projects-etl opendataservices/resource-projects-etl:${TRAVIS_TAG:-$TRAVIS_BRANCH}; docker push opendataservices/resource-projects-etl:${TRAVIS_TAG:-$TRAVIS_BRANCH}; fi
