PREFIX rp: <http://resourceprojects.org/def/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>


select distinct ?company ?label ?country ?operationsIn ?activeOn

where 
{
?company a rp:Company.
?company skos:prefLabel ?label.

OPTIONAL {
  ?company rp:hasLocation ?country.
  ?country a rp:Country.
} 
OPTIONAL {
  ?company rp:hasStakeholding ?stake.
  ?stake rp:isStakeIn ?project.
  ?project rp:hasLocation ?operationsIn.
  ?operationsIn a rp:Country.
  ?project rp:trueAt ?activeOn. ## ToDo: Improve query to only fetch most recent active date. 
}
FILTER(STRLEN(?label)>2)

} LIMIT 100